# --- CORRECTED FILE: backend/data/migrations/versions/<new_revision_id>_phase_10_add_repository_institution_affiliation_table.py ---
# Note: The revision ID and Create Date will be DIFFERENT when you regenerate it.

"""Phase 10: Add repository_institution_affiliation table

Revision ID: <new_revision_id> # Replace with actual new ID
Revises: c9b46f9c64e5
Create Date: YYYY-MM-DD HH:MM:SS.ffffff # Replace with actual new timestamp

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '<new_revision_id>' # Replace with actual new ID
down_revision: Union[str, None] = 'c9b46f9c64e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - START ###
    op.create_table('repository_institution_affiliations',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_name', sa.String(), nullable=False),
    sa.Column('algorithm_version', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repository_id', 'institution_id', 'algorithm_name', 'algorithm_version')
    )
    op.create_index('ix_repo_inst_affil_algo_name', 'repository_institution_affiliations', ['algorithm_name'], unique=False)
    op.create_index('ix_repo_inst_affil_inst_id', 'repository_institution_affiliations', ['institution_id'], unique=False)
    op.create_index('ix_repo_inst_affil_repo_id', 'repository_institution_affiliations', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - START ###
    op.drop_index('ix_repo_inst_affil_repo_id', table_name='repository_institution_affiliations')
    op.drop_index('ix_repo_inst_affil_inst_id', table_name='repository_institution_affiliations')
    op.drop_index('ix_repo_inst_affil_algo_name', table_name='repository_institution_affiliations')
    op.drop_table('repository_institution_affiliations')
    # ### end Alembic commands ###