"""Phase 2: Add keyword search models

Revision ID: 1cc8bbb9702b
Revises: ac00d539ca94
Create Date: 2025-04-07 06:37:53.016044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1cc8bbb9702b"
down_revision: Union[str, None] = "ac00d539ca94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keyword_search_sessions",
        sa.Column("keywords_raw", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("results_count", sa.Integer(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_keyword_search_sessions_id"),
        "keyword_search_sessions",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_keyword_search_sessions_status",
        "keyword_search_sessions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "keyword_repository_associations",
        sa.Column("keyword_search_session_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column(
            "match_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["keyword_search_session_id"],
            ["keyword_search_sessions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("keyword_search_session_id", "repository_id"),
    )
    op.create_index(
        op.f("ix_keyword_repository_associations_keyword_search_session_id"),
        "keyword_repository_associations",
        ["keyword_search_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_keyword_repository_associations_repository_id"),
        "keyword_repository_associations",
        ["repository_id"],
        unique=False,
    )
    # op.create_unique_constraint('uq_repo_contrib', 'repository_contributors', ['repository_id', 'contributor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_repo_contrib", "repository_contributors", type_="unique")
    op.drop_index(
        op.f("ix_keyword_repository_associations_repository_id"),
        table_name="keyword_repository_associations",
    )
    op.drop_index(
        op.f("ix_keyword_repository_associations_keyword_search_session_id"),
        table_name="keyword_repository_associations",
    )
    op.drop_table("keyword_repository_associations")
    op.drop_index(
        "ix_keyword_search_sessions_status", table_name="keyword_search_sessions"
    )
    op.drop_index(
        op.f("ix_keyword_search_sessions_id"), table_name="keyword_search_sessions"
    )
    op.drop_table("keyword_search_sessions")
    # ### end Alembic commands ###
