"""Allow null entity_id in entity discovery associations

Revision ID: 3ab81a4cf052
Revises: a7e01fc1d2e8
Create Date: 2025-04-07 14:32:07.068379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ab81a4cf052"
down_revision: Union[str, None] = "a7e01fc1d2e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "entity_discovery_associations",
        "entity_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # --- REMOVE THIS LINE ---
    # op.create_unique_constraint('uq_repo_contrib', 'repository_contributors', ['repository_id', 'contributor_id'])
    # --- END REMOVAL ---
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- REMOVE THIS LINE ---
    # op.drop_constraint('uq_repo_contrib', 'repository_contributors', type_='unique')
    # --- END REMOVAL ---
    op.alter_column(
        "entity_discovery_associations",
        "entity_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
