# --- CORRECTED MIGRATION FILE: backend/data/migrations/versions/4c5ec8e48a9c_phase_19_add_domain_field_subfield_topic_worktopic_.py ---

"""Phase 19: Add Domain, Field, Subfield, Topic, WorkTopic models

Revision ID: 4c5ec8e48a9c
Revises: dd1449ba853a
Create Date: 2025-04-15 21:48:21.467935 # Or your actual timestamp

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c5ec8e48a9c"
down_revision: Union[str, None] = "dd1449ba853a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - START ###
    op.create_table(
        "domains",
        sa.Column("openalex_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domains_display_name"), "domains", ["display_name"], unique=False
    )
    op.create_index(op.f("ix_domains_id"), "domains", ["id"], unique=False)
    op.create_index(
        op.f("ix_domains_openalex_id"), "domains", ["openalex_id"], unique=True
    )
    op.create_table(
        "fields",
        sa.Column("openalex_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Using op.f for consistency where possible
    op.create_index(
        op.f("ix_fields_display_name"), "fields", ["display_name"], unique=False
    )
    op.create_index(op.f("ix_fields_domain_id"), "fields", ["domain_id"], unique=False)
    op.create_index(op.f("ix_fields_id"), "fields", ["id"], unique=False)
    op.create_index(
        op.f("ix_fields_openalex_id"), "fields", ["openalex_id"], unique=True
    )
    op.create_table(
        "subfields",
        sa.Column("openalex_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Using op.f for consistency where possible
    op.create_index(
        op.f("ix_subfields_display_name"), "subfields", ["display_name"], unique=False
    )
    op.create_index(
        op.f("ix_subfields_field_id"), "subfields", ["field_id"], unique=False
    )
    op.create_index(op.f("ix_subfields_id"), "subfields", ["id"], unique=False)
    # --- CORRECTION HERE: unique=True ---
    op.create_index(
        op.f("ix_subfields_openalex_id"), "subfields", ["openalex_id"], unique=True
    )
    # --- END CORRECTION ---
    op.create_table(
        "topics",
        sa.Column("openalex_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("subfield_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subfield_id"], ["subfields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topics_display_name"), "topics", ["display_name"], unique=False
    )
    op.create_index(op.f("ix_topics_id"), "topics", ["id"], unique=False)
    op.create_index(
        op.f("ix_topics_openalex_id"), "topics", ["openalex_id"], unique=True
    )
    # Using op.f for consistency where possible
    op.create_index(
        op.f("ix_topics_subfield_id"), "topics", ["subfield_id"], unique=False
    )
    op.create_table(
        "work_topics",
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("work_id", "topic_id"),
    )
    op.create_index(
        op.f("ix_work_topics_topic_id"), "work_topics", ["topic_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_topics_work_id"), "work_topics", ["work_id"], unique=False
    )
    # --- REMOVED UNRELATED PERSONS INDEX CHANGES ---
    # op.drop_index('ix_persons_orcid', table_name='persons')
    # op.create_index('ix_persons_orcid', 'persons', ['orcid'], unique=False)
    # --- END REMOVAL ---
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - START ###
    # --- REMOVED UNRELATED PERSONS INDEX CHANGES ---
    # op.drop_index('ix_persons_orcid', table_name='persons')
    # op.create_index('ix_persons_orcid', 'persons', ['orcid'], unique=True)
    # --- END REMOVAL ---
    op.drop_index(op.f("ix_work_topics_work_id"), table_name="work_topics")
    op.drop_index(op.f("ix_work_topics_topic_id"), table_name="work_topics")
    op.drop_table("work_topics")
    op.drop_index(op.f("ix_topics_subfield_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_openalex_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_display_name"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_subfields_openalex_id"), table_name="subfields")
    op.drop_index(op.f("ix_subfields_id"), table_name="subfields")
    op.drop_index(op.f("ix_subfields_field_id"), table_name="subfields")
    op.drop_index(op.f("ix_subfields_display_name"), table_name="subfields")
    op.drop_table("subfields")
    op.drop_index(op.f("ix_fields_openalex_id"), table_name="fields")
    op.drop_index(op.f("ix_fields_id"), table_name="fields")
    op.drop_index(op.f("ix_fields_domain_id"), table_name="fields")
    op.drop_index(op.f("ix_fields_display_name"), table_name="fields")
    op.drop_table("fields")
    op.drop_index(op.f("ix_domains_openalex_id"), table_name="domains")
    op.drop_index(op.f("ix_domains_id"), table_name="domains")
    op.drop_index(op.f("ix_domains_display_name"), table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
