# --- CORRECTED MIGRATION SCRIPT: backend/data/migrations/versions/6caa9c3d1fa0_phase_21_add_pullrequest_issue_comment_models.py ---

"""Phase 21: Add PullRequest, Issue, Comment models

Revision ID: 6caa9c3d1fa0
Revises: d19968da140c # Assuming this was the previous correct head
Create Date: 2025-04-30 17:11:24.546255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6caa9c3d1fa0"
down_revision: Union[str, None] = (
    "d19968da140c"  # Ensure this points to your actual previous revision
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - START ###
    op.create_table(
        "issues",
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("gh_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gh_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gh_closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issues_github_id"), "issues", ["github_id"], unique=True)
    op.create_index(op.f("ix_issues_id"), "issues", ["id"], unique=False)
    op.create_index("ix_issues_number", "issues", ["number"], unique=False)
    op.create_index("ix_issues_repo_id", "issues", ["repository_id"], unique=False)
    op.create_index(
        "ix_issues_repo_number", "issues", ["repository_id", "number"], unique=False
    )
    op.create_index(
        op.f("ix_issues_repository_id"), "issues", ["repository_id"], unique=False
    )  # Keep op.f if generated
    op.create_index("ix_issues_state", "issues", ["state"], unique=False)
    op.create_index("ix_issues_user_id", "issues", ["user_id"], unique=False)
    op.create_table(
        "pull_requests",
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("gh_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gh_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gh_closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gh_merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pull_requests_github_id"), "pull_requests", ["github_id"], unique=True
    )
    op.create_index(op.f("ix_pull_requests_id"), "pull_requests", ["id"], unique=False)
    op.create_index(
        "ix_pull_requests_number", "pull_requests", ["number"], unique=False
    )
    op.create_index(
        "ix_pull_requests_repo_id", "pull_requests", ["repository_id"], unique=False
    )
    op.create_index(
        "ix_pull_requests_repo_number",
        "pull_requests",
        ["repository_id", "number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pull_requests_repository_id"),
        "pull_requests",
        ["repository_id"],
        unique=False,
    )  # Keep op.f if generated
    op.create_index("ix_pull_requests_state", "pull_requests", ["state"], unique=False)
    op.create_index(
        op.f("ix_pull_requests_user_id"), "pull_requests", ["user_id"], unique=False
    )  # Keep op.f if generated
    op.create_table(
        "issue_comments",
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("gh_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gh_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_issue_comments_github_id"),
        "issue_comments",
        ["github_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_issue_comments_id"), "issue_comments", ["id"], unique=False
    )
    op.create_index(
        "ix_issue_comments_issue_id", "issue_comments", ["issue_id"], unique=False
    )
    op.create_index(
        "ix_issue_comments_user_id", "issue_comments", ["user_id"], unique=False
    )
    op.create_table(
        "pr_review_comments",
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("pull_request_review_id", sa.BigInteger(), nullable=True),
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("gh_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gh_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pr_id"], ["pull_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pr_review_comments_github_id"),
        "pr_review_comments",
        ["github_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_pr_review_comments_id"), "pr_review_comments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pr_review_comments_pr_id"),
        "pr_review_comments",
        ["pr_id"],
        unique=False,
    )  # Keep op.f if generated
    op.create_index(
        "ix_pr_review_comments_review_id",
        "pr_review_comments",
        ["pull_request_review_id"],
        unique=False,
    )
    op.create_index(
        "ix_pr_review_comments_user_id", "pr_review_comments", ["user_id"], unique=False
    )

    # --- REMOVED UNRELATED INDEX CHANGES ---
    # op.drop_index('ix_fields_openalex_id', table_name='fields')
    # op.create_index('ix_fields_openalex_id', 'fields', ['openalex_id'], unique=False)
    # op.drop_index('ix_institutions_ror', table_name='institutions')
    # op.create_index(op.f('ix_institutions_ror'), 'institutions', ['ror'], unique=True)
    # op.drop_index('ix_topics_openalex_id', table_name='topics')
    # op.create_index('ix_topics_openalex_id', 'topics', ['openalex_id'], unique=False)
    # --- END REMOVAL ---
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - START ###
    # --- REMOVED UNRELATED INDEX CHANGES ---
    # op.drop_index('ix_topics_openalex_id', table_name='topics')
    # op.create_index('ix_topics_openalex_id', 'topics', ['openalex_id'], unique=True)
    # op.drop_index(op.f('ix_institutions_ror'), table_name='institutions')
    # op.create_index('ix_institutions_ror', 'institutions', ['ror'], unique=False)
    # op.drop_index('ix_fields_openalex_id', table_name='fields')
    # op.create_index('ix_fields_openalex_id', 'fields', ['openalex_id'], unique=True)
    # --- END REMOVAL ---

    op.drop_index("ix_pr_review_comments_user_id", table_name="pr_review_comments")
    op.drop_index("ix_pr_review_comments_review_id", table_name="pr_review_comments")
    op.drop_index(op.f("ix_pr_review_comments_pr_id"), table_name="pr_review_comments")
    op.drop_index(op.f("ix_pr_review_comments_id"), table_name="pr_review_comments")
    op.drop_index(
        op.f("ix_pr_review_comments_github_id"), table_name="pr_review_comments"
    )
    op.drop_table("pr_review_comments")
    op.drop_index("ix_issue_comments_user_id", table_name="issue_comments")
    op.drop_index("ix_issue_comments_issue_id", table_name="issue_comments")
    op.drop_index(op.f("ix_issue_comments_id"), table_name="issue_comments")
    op.drop_index(op.f("ix_issue_comments_github_id"), table_name="issue_comments")
    op.drop_table("issue_comments")
    op.drop_index(op.f("ix_pull_requests_user_id"), table_name="pull_requests")
    op.drop_index("ix_pull_requests_state", table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_repository_id"), table_name="pull_requests")
    op.drop_index("ix_pull_requests_repo_number", table_name="pull_requests")
    op.drop_index("ix_pull_requests_repo_id", table_name="pull_requests")
    op.drop_index("ix_pull_requests_number", table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_github_id"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index("ix_issues_user_id", table_name="issues")
    op.drop_index("ix_issues_state", table_name="issues")
    op.drop_index(op.f("ix_issues_repository_id"), table_name="issues")
    op.drop_index("ix_issues_repo_number", table_name="issues")
    op.drop_index("ix_issues_repo_id", table_name="issues")
    op.drop_index("ix_issues_number", table_name="issues")
    op.drop_index(op.f("ix_issues_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_github_id"), table_name="issues")
    op.drop_table("issues")
    # ### end Alembic commands ###
