"""Phase 3: Add scholarly entity models (Person, Institution, Authorship, Affiliation, Citation)

Revision ID: a7e01fc1d2e8
Revises: 1cc8bbb9702b
Create Date: 2025-04-07 11:19:41.305053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7e01fc1d2e8'
down_revision: Union[str, None] = '1cc8bbb9702b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - START ###
    op.create_table('institutions',
    sa.Column('openalex_id', sa.String(), nullable=False),
    sa.Column('ror', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_display_name'), 'institutions', ['display_name'], unique=False)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_openalex_id'), 'institutions', ['openalex_id'], unique=True)
    op.create_index(op.f('ix_institutions_ror'), 'institutions', ['ror'], unique=True)
    op.create_index('ix_institutions_type', 'institutions', ['type'], unique=False) # Keep non-unique as per model
    op.create_table('persons',
    sa.Column('openalex_id', sa.String(), nullable=False),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('display_name_alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # --- CORRECTED INDEXES for persons ---
    op.create_index(op.f('ix_persons_display_name'), 'persons', ['display_name'], unique=False) # Keep non-unique as per model
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index('ix_persons_openalex_id', 'persons', ['openalex_id'], unique=True) # Changed to unique=True
    op.create_index('ix_persons_orcid', 'persons', ['orcid'], unique=True) # Changed to unique=True
    # --- END CORRECTIONS ---
    op.create_table('authorships',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('author_position', sa.String(), nullable=True),
    sa.Column('is_corresponding', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'person_id')
    )
    op.create_index('ix_authorships_person_id', 'authorships', ['person_id'], unique=False)
    op.create_index('ix_authorships_work_id', 'authorships', ['work_id'], unique=False)
    op.create_table('work_citations',
    sa.Column('citing_work_id', sa.Integer(), nullable=False),
    sa.Column('cited_work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cited_work_id'], ['works.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citing_work_id', 'cited_work_id')
    )
    op.create_index('ix_work_citations_cited_work_id', 'work_citations', ['cited_work_id'], unique=False)
    op.create_index('ix_work_citations_citing_work_id', 'work_citations', ['citing_work_id'], unique=False)
    op.create_table('affiliations',
    sa.Column('authorship_work_id', sa.Integer(), nullable=False),
    sa.Column('authorship_person_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorship_work_id', 'authorship_person_id'], ['authorships.work_id', 'authorships.person_id'], name='fk_affiliation_authorship', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('authorship_work_id', 'authorship_person_id', 'institution_id')
    )
    op.create_index('ix_affiliations_authorship_person_id', 'affiliations', ['authorship_person_id'], unique=False)
    op.create_index('ix_affiliations_authorship_work_id', 'affiliations', ['authorship_work_id'], unique=False)
    op.create_index('ix_affiliations_institution_id', 'affiliations', ['institution_id'], unique=False)
    # --- REMOVED REDUNDANT CONSTRAINT ---
    # op.create_unique_constraint('uq_repo_contrib', 'repository_contributors', ['repository_id', 'contributor_id'])
    # --- END REMOVAL ---
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - START ###
    # --- REMOVED REDUNDANT CONSTRAINT DROP ---
    # op.drop_constraint('uq_repo_contrib', 'repository_contributors', type_='unique')
    # --- END REMOVAL ---
    op.drop_index('ix_affiliations_institution_id', table_name='affiliations')
    op.drop_index('ix_affiliations_authorship_work_id', table_name='affiliations')
    op.drop_index('ix_affiliations_authorship_person_id', table_name='affiliations')
    op.drop_table('affiliations')
    op.drop_index('ix_work_citations_citing_work_id', table_name='work_citations')
    op.drop_index('ix_work_citations_cited_work_id', table_name='work_citations')
    op.drop_table('work_citations')
    op.drop_index('ix_authorships_work_id', table_name='authorships')
    op.drop_index('ix_authorships_person_id', table_name='authorships')
    op.drop_table('authorships')
    # --- CORRECTED INDEX DROPS for persons ---
    op.drop_index('ix_persons_orcid', table_name='persons') # Was unique=True
    op.drop_index('ix_persons_openalex_id', table_name='persons') # Was unique=True
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_display_name'), table_name='persons')
    # --- END CORRECTIONS ---
    op.drop_table('persons')
    op.drop_index('ix_institutions_type', table_name='institutions')
    op.drop_index(op.f('ix_institutions_ror'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_openalex_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_display_name'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###