"""Phase 1: Initial core schema with hierarchical discovery

Revision ID: ac00d539ca94
Revises: 
Create Date: 2025-04-05 09:31:05.488592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac00d539ca94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_github_id'), 'contributors', ['github_id'], unique=True)
    op.create_index(op.f('ix_contributors_id'), 'contributors', ['id'], unique=False)
    op.create_index(op.f('ix_contributors_login'), 'contributors', ['login'], unique=True)
    op.create_index(op.f('ix_contributors_type'), 'contributors', ['type'], unique=False)
    op.create_table('discovery_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_chain_id', sa.UUID(), nullable=True),
    sa.Column('root_chain_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('discovery_type', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_chain_id'], ['discovery_chains.id'], ),
    sa.ForeignKeyConstraint(['root_chain_id'], ['discovery_chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_chains_root_chain_id'), 'discovery_chains', ['root_chain_id'], unique=False)
    op.create_index('ix_discovery_chains_root_id', 'discovery_chains', ['root_chain_id'], unique=False)
    op.create_index(op.f('ix_discovery_chains_status'), 'discovery_chains', ['status'], unique=False)
    op.create_table('owners',
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_github_id'), 'owners', ['github_id'], unique=True)
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_owners_login'), 'owners', ['login'], unique=True)
    op.create_index(op.f('ix_owners_type'), 'owners', ['type'], unique=False)
    op.create_table('works',
    sa.Column('openalex_id', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('host_venue_display_name', sa.String(), nullable=True),
    sa.Column('openalex_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_doi'), 'works', ['doi'], unique=True)
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_index(op.f('ix_works_openalex_id'), 'works', ['openalex_id'], unique=True)
    op.create_index(op.f('ix_works_publication_year'), 'works', ['publication_year'], unique=False)
    op.create_index('ix_works_type', 'works', ['type'], unique=False)
    op.create_table('entity_discovery_associations',
    sa.Column('discovery_chain_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_direct_discovery', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discovery_chain_id'], ['discovery_chains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discovery_chain_id', 'entity_type', 'entity_id', name='uq_discovery_entity')
    )
    op.create_index(op.f('ix_entity_discovery_associations_discovery_chain_id'), 'entity_discovery_associations', ['discovery_chain_id'], unique=False)
    op.create_index(op.f('ix_entity_discovery_associations_entity_id'), 'entity_discovery_associations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_discovery_associations_entity_type'), 'entity_discovery_associations', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_discovery_associations_id'), 'entity_discovery_associations', ['id'], unique=False)
    op.create_index('ix_entity_discovery_chain_id', 'entity_discovery_associations', ['discovery_chain_id'], unique=False)
    op.create_index('ix_entity_discovery_entity', 'entity_discovery_associations', ['entity_type', 'entity_id'], unique=False)
    op.create_table('repositories',
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('stargazers_count', sa.Integer(), nullable=False),
    sa.Column('watchers_count', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('gh_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gh_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gh_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=True)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_language'), 'repositories', ['language'], unique=False)
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_table('doi_references',
    sa.Column('doi', sa.String(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'doi', 'source_file', name='uq_repo_doi_source')
    )
    op.create_index('ix_doi_references_doi', 'doi_references', ['doi'], unique=False)
    op.create_index(op.f('ix_doi_references_id'), 'doi_references', ['id'], unique=False)
    op.create_index(op.f('ix_doi_references_repository_id'), 'doi_references', ['repository_id'], unique=False)
    op.create_index(op.f('ix_doi_references_work_id'), 'doi_references', ['work_id'], unique=False)
    op.create_table('repository_contributors',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('contributions_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('repository_id', 'contributor_id'),
    sa.UniqueConstraint('repository_id', 'contributor_id', name='uq_repo_contrib')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_contributors')
    op.drop_index(op.f('ix_doi_references_work_id'), table_name='doi_references')
    op.drop_index(op.f('ix_doi_references_repository_id'), table_name='doi_references')
    op.drop_index(op.f('ix_doi_references_id'), table_name='doi_references')
    op.drop_index('ix_doi_references_doi', table_name='doi_references')
    op.drop_table('doi_references')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_language'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index('ix_entity_discovery_entity', table_name='entity_discovery_associations')
    op.drop_index('ix_entity_discovery_chain_id', table_name='entity_discovery_associations')
    op.drop_index(op.f('ix_entity_discovery_associations_id'), table_name='entity_discovery_associations')
    op.drop_index(op.f('ix_entity_discovery_associations_entity_type'), table_name='entity_discovery_associations')
    op.drop_index(op.f('ix_entity_discovery_associations_entity_id'), table_name='entity_discovery_associations')
    op.drop_index(op.f('ix_entity_discovery_associations_discovery_chain_id'), table_name='entity_discovery_associations')
    op.drop_table('entity_discovery_associations')
    op.drop_index('ix_works_type', table_name='works')
    op.drop_index(op.f('ix_works_publication_year'), table_name='works')
    op.drop_index(op.f('ix_works_openalex_id'), table_name='works')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_index(op.f('ix_works_doi'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_owners_type'), table_name='owners')
    op.drop_index(op.f('ix_owners_login'), table_name='owners')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_github_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_discovery_chains_status'), table_name='discovery_chains')
    op.drop_index('ix_discovery_chains_root_id', table_name='discovery_chains')
    op.drop_index(op.f('ix_discovery_chains_root_chain_id'), table_name='discovery_chains')
    op.drop_table('discovery_chains')
    op.drop_index(op.f('ix_contributors_type'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_login'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_id'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_github_id'), table_name='contributors')
    op.drop_table('contributors')
    # ### end Alembic commands ###
