"""Phase 6: Add topics and license to Repository

Revision ID: c9b46f9c64e5
Revises: 3ab81a4cf052
Create Date: 2025-04-08 17:36:44.473362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9b46f9c64e5'
down_revision: Union[str, None] = '3ab81a4cf052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - START ###
    # --- REMOVED ORCID INDEX CHANGES ---
    # op.drop_index('ix_persons_orcid', table_name='persons')
    # op.create_index('ix_persons_orcid', 'persons', ['orcid'], unique=False)
    # --- END REMOVAL ---

    # Correct: Adds topics column
    op.add_column('repositories', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Correct: Adds license column
    op.add_column('repositories', sa.Column('license', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - START ###
    # Correct: Drops license column
    op.drop_column('repositories', 'license')
    # Correct: Drops topics column
    op.drop_column('repositories', 'topics')

    # --- REMOVED ORCID INDEX CHANGES ---
    # op.drop_index('ix_persons_orcid', table_name='persons')
    # op.create_index('ix_persons_orcid', 'persons', ['orcid'], unique=True)
    # --- END REMOVAL ---
    # ### end Alembic commands ###