"""Phase 19: Add Concept and WorkConcept models

Revision ID: d19968da140c
Revises: 4c5ec8e48a9c
Create Date: 2025-04-16 10:43:42.466277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19968da140c'
down_revision: Union[str, None] = '4c5ec8e48a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domains_openalex_id', table_name='domains')
    op.create_index('ix_domains_openalex_id', 'domains', ['openalex_id'], unique=False)
    op.drop_index('ix_institutions_ror', table_name='institutions')
    op.create_index('ix_institutions_ror', 'institutions', ['ror'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_institutions_ror', table_name='institutions')
    op.create_index('ix_institutions_ror', 'institutions', ['ror'], unique=True)
    op.drop_index('ix_domains_openalex_id', table_name='domains')
    op.create_index('ix_domains_openalex_id', 'domains', ['openalex_id'], unique=True)
    # ### end Alembic commands ###
