"""Phase 18: Add software_dependency table

Revision ID: dd1449ba853a
Revises: ed4cc55634bf
Create Date: 2025-04-12 21:52:53.470471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1449ba853a'
down_revision: Union[str, None] = 'ed4cc55634bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_dependencies',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('dependency_name', sa.String(), nullable=False),
    sa.Column('version_constraint', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('is_dev_dependency', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_dependencies_dependency_name'), 'software_dependencies', ['dependency_name'], unique=False)
    op.create_index(op.f('ix_software_dependencies_dependency_type'), 'software_dependencies', ['dependency_type'], unique=False)
    op.create_index(op.f('ix_software_dependencies_id'), 'software_dependencies', ['id'], unique=False)
    op.create_index('ix_software_dependencies_is_dev', 'software_dependencies', ['is_dev_dependency'], unique=False)
    op.create_index(op.f('ix_software_dependencies_is_dev_dependency'), 'software_dependencies', ['is_dev_dependency'], unique=False)
    op.create_index('ix_software_dependencies_name', 'software_dependencies', ['dependency_name'], unique=False)
    op.create_index('ix_software_dependencies_repo_id', 'software_dependencies', ['repository_id'], unique=False)
    op.create_index(op.f('ix_software_dependencies_repository_id'), 'software_dependencies', ['repository_id'], unique=False)
    op.create_index('ix_software_dependencies_type', 'software_dependencies', ['dependency_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_software_dependencies_type', table_name='software_dependencies')
    op.drop_index(op.f('ix_software_dependencies_repository_id'), table_name='software_dependencies')
    op.drop_index('ix_software_dependencies_repo_id', table_name='software_dependencies')
    op.drop_index('ix_software_dependencies_name', table_name='software_dependencies')
    op.drop_index(op.f('ix_software_dependencies_is_dev_dependency'), table_name='software_dependencies')
    op.drop_index('ix_software_dependencies_is_dev', table_name='software_dependencies')
    op.drop_index(op.f('ix_software_dependencies_id'), table_name='software_dependencies')
    op.drop_index(op.f('ix_software_dependencies_dependency_type'), table_name='software_dependencies')
    op.drop_index(op.f('ix_software_dependencies_dependency_name'), table_name='software_dependencies')
    op.drop_table('software_dependencies')
    # ### end Alembic commands ###
