"""Phase 10.3: Add github_organization_logins to Institution

Revision ID: ed4cc55634bf
Revises: <new_revision_id>
Create Date: 2025-04-11 08:18:38.324876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed4cc55634bf"
down_revision: Union[str, None] = "<new_revision_id>"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "institutions",
        sa.Column(
            "github_organization_logins",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("institutions", "github_organization_logins")
    # ### end Alembic commands ###
