"""
backend.data.models.repository_institution_affiliation
------------------------------------------------------
This module defines the RepositoryInstitutionAffiliation model, representing
a calculated or inferred link between a Repository and an Institution,
along with metadata about how this link was determined (e.g., algorithm, confidence).
"""

import logging
from typing import Dict, Any, Optional, TYPE_CHECKING

from sqlalchemy import String, Float, ForeignKey, Index, PrimaryKeyConstraint

# Import JSONB type for storing structured evidence/parameters in PostgreSQL
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship, Mapped, mapped_column

# Assuming Base is correctly defined elsewhere
# Adjust import path as necessary
from ..database import Base

# Import custom timestamp types for consistency
from .types import (
    timestamp_created,
)  # Using created timestamp logic for calculation time

# Use TYPE_CHECKING to prevent circular imports for type hints
if TYPE_CHECKING:
    from .repository import Repository
    from .institution import Institution

logger = logging.getLogger(__name__)


class RepositoryInstitutionAffiliation(Base):
    """
    Represents a potential affiliation link between a Repository and an Institution.

    This model stores the results of affiliation prediction algorithms. Each record
    represents a specific affiliation hypothesis generated by a particular algorithm
    version, linking one repository to one institution with an associated confidence
    score and evidence.

    It uses a composite primary key to uniquely identify an affiliation result based
    on the repository, institution, and the algorithm that produced it. It inherits
    directly from `Base`.

    Attributes:
        repository_id: Foreign key linking to the Repository. Part of the composite PK.
        institution_id: Foreign key linking to the Institution. Part of the composite PK.
        algorithm_name: Name of the algorithm that generated this affiliation link. Part of the composite PK.
        algorithm_version: Version of the algorithm used. Part of the composite PK.
        confidence_score: The score (e.g., probability, certainty) assigned by the algorithm.
        evidence: JSON field storing data points used as evidence for this affiliation.
        parameters_used: JSON field storing the parameters the algorithm ran with.
        calculated_at: Timestamp indicating when this specific affiliation record was generated.
        repository: Relationship back to the Repository object.
        institution: Relationship back to the Institution object.
    """

    __tablename__ = "repository_institution_affiliations"

    # --- Composite Primary Key Components ---
    # Uniquely identifies a specific affiliation result generated by a specific algorithm run.

    # Foreign key to the Repository being linked.
    repository_id: Mapped[int] = mapped_column(
        ForeignKey("repositories.id", ondelete="CASCADE"),
        primary_key=True,
        # `ondelete="CASCADE"`: If the repository is deleted, associated affiliation results are removed.
    )
    # Foreign key to the Institution being linked.
    institution_id: Mapped[int] = mapped_column(
        ForeignKey("institutions.id", ondelete="CASCADE"),
        primary_key=True,
        # `ondelete="CASCADE"`: If the institution is deleted, associated affiliation results are removed.
    )
    # Identifier for the affiliation prediction algorithm used.
    algorithm_name: Mapped[str] = mapped_column(String, primary_key=True)
    # Version string for the algorithm to track changes/updates.
    algorithm_version: Mapped[str] = mapped_column(String, primary_key=True)

    # --- Affiliation Details and Provenance ---
    # Stores the output and context of the affiliation algorithm.

    # Numerical score indicating the strength or likelihood of the affiliation.
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)
    # Flexible storage for evidence supporting the affiliation.
    # Example: {'matched_contributors': ['user1', 'user2'], 'email_domains': ['example.edu']}
    evidence: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSONB, nullable=True)
    # Records the parameters used by the algorithm for this specific run.
    # Example: {'threshold': 0.7, 'use_email_heuristics': True}
    parameters_used: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB, nullable=True
    )

    # --- Timestamping ---
    # Indicates when this specific affiliation record was created/calculated.
    # Uses the `timestamp_created` type which typically sets `server_default=func.now()`.
    calculated_at: Mapped[timestamp_created]

    # --- Relationships ---
    # Allows navigation back to the related Repository and Institution.

    # Relationship to the associated Repository.
    # No `back_populates` needed if Repository doesn't link back to these affiliations directly.
    repository: Mapped["Repository"] = relationship()
    # Relationship to the associated Institution.
    # No `back_populates` needed if Institution doesn't link back directly.
    institution: Mapped["Institution"] = relationship()

    # --- Table Arguments ---
    # Define the composite primary key constraint explicitly and add indexes.
    __table_args__ = (
        # Explicit definition of the composite primary key constraint.
        PrimaryKeyConstraint(
            "repository_id", "institution_id", "algorithm_name", "algorithm_version"
        ),
        # Indexes on individual foreign key columns and algorithm name facilitate efficient
        # lookups, e.g., finding all affiliations for a repo, or all results from a specific algorithm.
        Index("ix_repo_inst_affil_repo_id", "repository_id"),
        Index("ix_repo_inst_affil_inst_id", "institution_id"),
        Index("ix_repo_inst_affil_algo_name", "algorithm_name"),
    )

    def __repr__(self):
        """Provides a concise string representation for debugging and logging."""
        return (
            f"<RepoInstAffil(repo={self.repository_id}, inst={self.institution_id}, "
            f"algo='{self.algorithm_name}_v{self.algorithm_version}', "
            f"score={self.confidence_score:.2f})>"
        )  # Format score for readability
